version: '3.7'

volumes:
  ipfs-data: {}

services:
  ipfs:
    image: ipfs/go-ipfs:v0.7.0
    command: ["daemon", "--migrate=true", "--enable-pubsub-experiment", "--offline"]
    volumes:
      - ipfs-data:/data/ipfs
    ports:
      - 5001:5001
    restart: unless-stopped
